### ISSUE TITLE
Try run the program

### ISSUE THREAD

**Issue by liorzemah** [sunwxg/decode_by_libwireshark#12]
I try run the program, i copy the myshark.c file  and frame_tvbuff.c file. When i try to compile the project i get this error from  frame_tvbuff.c  :

../../libwireshark2/decode_by_libwireshark/include/file.h:405:54: error: unknown type name ‘print_args_t’
 cf_print_status_t cf_print_packets(capture_file *cf, print_args_t *print_args);

**Comment by sunwxg** [comment]
I don't know how you compile the project.

**Comment by liorzemah** [comment]
I work with CodeBlocks, when i try to build my project i get the error in the first comment.


gcc -Wall -fexceptions -g -I../../libwireshark2/decode_by_libwireshark/include -I../../../../../usr/include/glib-2.0 -I../../../../../usr/lib/x86_64-linux-gnu/glib-2.0 -I../../../../../usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../../Downloads/wireshark-2.4.1 -I../../libwireshark2/decode_by_libwireshark/.git -I../../../Downloads/wireshark-2.4.1/wsutil -I../../../Downloads/wireshark-2.4.1/wiretap -I/home/lior/Documents/libwireshark2/decode_by_libwireshark/include -I/usr/include -I/home/lior/Documents/libwireshark2/decode_by_libwireshark/include/wireshark -I/home/lior/Downloads/glib-master -I/usr/include/glib-2.0 -I/home/lior/Downloads/wireshark-2.4.1 -c "/home/lior/Documents/TryCodeBlock/Try/ frame_tvbuff.c" -o "obj/Debug/ frame_tvbuff.o"
In file included from ../../libwireshark2/decode_by_libwireshark/include/globals.h:26:0,
                 from /home/lior/Documents/TryCodeBlock/Try/ frame_tvbuff.c:32:
../../libwireshark2/decode_by_libwireshark/include/file.h:405:54: error: unknown type name ‘print_args_t’
 cf_print_status_t cf_print_packets(capture_file *cf, print_args_t *print_args);
                                                      ^
../../libwireshark2/decode_by_libwireshark/include/file.h:414:59: error: unknown type name ‘print_args_t’
 cf_print_status_t cf_write_pdml_packets(capture_file *cf, print_args_t *print_args);
                                                           ^
../../libwireshark2/decode_by_libwireshark/include/file.h:423:59: error: unknown type name ‘print_args_t’
 cf_print_status_t cf_write_psml_packets(capture_file *cf, print_args_t *print_args);
                                                           ^
../../libwireshark2/decode_by_libwireshark/include/file.h:432:58: error: unknown type name ‘print_args_t’
 cf_print_status_t cf_write_csv_packets(capture_file *cf, print_args_t *print_args);
                                                          ^
../../libwireshark2/decode_by_libwireshark/include/file.h:441:62: error: unknown type name ‘print_args_t’
 cf_print_status_t cf_write_carrays_packets(capture_file *cf, print_args_t *print_args);
                                                              ^
/home/lior/Documents/TryCodeBlock/Try/ frame_tvbuff.c: In function ‘frame_read’:
/home/lior/Documents/TryCodeBlock/Try/ frame_tvbuff.c:62:9: error: ‘WTAP_ERR_UNSUPPORTED_ENCAP’ undeclared (first use in this function)
    case WTAP_ERR_UNSUPPORTED_ENCAP:

**Comment by sunwxg** [comment]
My code only work on version 1.12.8, it can't work with newer wireshark.
You should use include files and .so files in my code folder.

**Comment by liorzemah** [comment]
alright, so i include only your files and your .so files and glib2.0 and glib-master, and when i try to build the project i get this error:

gcc -Wall -g -I../../libwireshark2/decode_by_libwireshark/include -I../../libwireshark2/decode_by_libwireshark/include/wireshark -I../../libwireshark2/decode_by_libwireshark/include/wireshark/epan -I../../libwireshark2/decode_by_libwireshark/include/wireshark/wiretap -I../../libwireshark2/decode_by_libwireshark/include/wireshark/wsutil -I/usr/include -I/home/lior/Downloads/glib-master -I/usr/include/glib-2.0 -c /home/lior/Documents/TryCodeBlock/TryInC/frame_tvbuff.c -o obj/Debug/frame_tvbuff.o
In file included from /usr/include/glib-2.0/glib/gtypes.h:32:0,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/lior/Documents/TryCodeBlock/TryInC/frame_tvbuff.c:25:
/home/lior/Downloads/glib-master/glibconfig.h:117:0: warning: "G_CAN_INLINE" redefined
 #define G_CAN_INLINE 1
 ^
In file included from /home/lior/Downloads/glib-master/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/lior/Documents/TryCodeBlock/TryInC/frame_tvbuff.c:25:
/usr/include/glib-2.0/glib/gmacros.h:64:0: note: this is the location of the previous definition
 #define G_CAN_INLINE
 ^
In file included from /usr/include/glib-2.0/glib.h:107:0,
                 from /home/lior/Documents/TryCodeBlock/TryInC/frame_tvbuff.c:25:
/usr/include/glib-2.0/glib/deprecated/gthread.h:131:0: warning: "g_static_mutex_get_mutex" redefined
 #define g_static_mutex_get_mutex g_static_mutex_get_mutex_impl
 ^
In file included from /usr/include/glib-2.0/glib/gtypes.h:32:0,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/lior/Documents/TryCodeBlock/TryInC/frame_tvbuff.c:25:
/home/lior/Downloads/glib-master/glibconfig.h:163:0: note: this is the location of the previous definition
 #define g_static_mutex_get_mutex(mutex) \
 ^
In file included from /usr/include/glib-2.0/glib.h:107:0,
                 from /home/lior/Documents/TryCodeBlock/TryInC/frame_tvbuff.c:25:
/usr/include/glib-2.0/glib/deprecated/gthread.h:132:0: warning: "G_STATIC_MUTEX_INIT" redefined
 #define G_STATIC_MUTEX_INIT { NULL }
 ^
In file included from /usr/include/glib-2.0/glib/gtypes.h:32:0,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/lior/Documents/TryCodeBlock/TryInC/frame_tvbuff.c:25:
/home/lior/Downloads/glib-master/glibconfig.h:162:0: note: this is the location of the previous definition
 #define G_STATIC_MUTEX_INIT { NULL, { { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0} } }
 ^
In file included from /usr/include/glib-2.0/glib.h:107:0,
                 from /home/lior/Documents/TryCodeBlock/TryInC/frame_tvbuff.c:25:
/usr/include/glib-2.0/glib/deprecated/gthread.h:140:3: error: conflicting types for ‘GStaticMutex’
 } GStaticMutex;
   ^
In file included from /usr/include/glib-2.0/glib/gtypes.h:32:0,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/lior/Documents/TryCodeBlock/TryInC/frame_tvbuff.c:25:
/home/lior/Downloads/glib-master/glibconfig.h:151:30: note: previous declaration of ‘GStaticMutex’ was here
 typedef struct _GStaticMutex GStaticMutex;
                              ^
Process terminated with status 1 (0 minute(s), 0 second(s))
1 error(s), 3 warning(s) (0 minute(s), 0 second(s))

**Comment by sunwxg** [comment]
Could you compile my code successfully?
Go to my code folder, do command 'make', is that successful?

**Comment by liorzemah** [comment]
yes it's work but when i try to complie with the command: gcc myshark , i get error.

root@lior-Lenovo-G570:/home/lior/Documents/libwireshark2/decode_by_libwireshark# gcc myshark
myshark: In function `_fini':
(.fini+0x0): multiple definition of `_fini'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o:(.fini+0x0): first defined here
myshark: In function `data_start':
(.data+0x0): multiple definition of `__data_start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o:(.data+0x0): first defined here
myshark: In function `data_start':
(.data+0x8): multiple definition of `__dso_handle'
/usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o:(.data+0x0): first defined here
myshark:(.rodata+0x0): multiple definition of `_IO_stdin_used'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o:(.rodata.cst4+0x0): first defined here
myshark: In function `_start':
(.text+0x0): multiple definition of `_start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o:(.text+0x0): first defined here
myshark: In function `_init':
(.init+0x0): multiple definition of `_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o:(.init+0x0): first defined here
/usr/lib/gcc/x86_64-linux-gnu/5/crtend.o:(.tm_clone_table+0x0): multiple definition of `__TMC_END__'
myshark:(.data+0x10): first defined here
/usr/bin/ld: error in myshark(.eh_frame); no .eh_frame_hdr table will be created.

**Comment by sunwxg** [comment]
You can see my Makefile, you should use these flags as your compile flags.
```
CFLAGS+= `pkg-config --cflags glib-2.0`
CFLAGS+= -I./include/wireshark
CFLAGS+= -I./include/wireshark/wiretap
CFLAGS+= -I./include
LDFLAGS= -L./libs -lwiretap -lwireshark -lwsutil -lglib-2.0
LDFLAGS+= -Wl,-rpath,./libs
```
The error when you compile your project is from glib, so I highly recommend you to use this as your compile flag.
> CFLAGS+= `pkg-config --cflags glib-2.0`
> LDFLAGS=  -lglib-2.0
